package com.jbpm.dmn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Car implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer mileage;
	private java.lang.Integer price;
	private java.lang.String type;

	public Car() {
	}

	public java.lang.Integer getMileage() {
		return this.mileage;
	}

	public void setMileage(java.lang.Integer mileage) {
		this.mileage = mileage;
	}

	public java.lang.Integer getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Integer price) {
		this.price = price;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public Car(java.lang.Integer mileage, java.lang.Integer price,
			java.lang.String type) {
		this.mileage = mileage;
		this.price = price;
		this.type = type;
	}

}